# Generated by Django 5.0.2 on 2024-12-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="project_technology",
            field=models.CharField(default="exit", max_length=512),
            preserve_default=False,
        ),
    ]
