# Generated by Django 5.1.3 on 2025-04-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projects_project_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='live_link',
            field=models.URLField(default='-'),
            preserve_default=False,
        ),
    ]
