# Generated by Django 5.1.3 on 2025-04-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projects_live_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
