# Generated by Django 5.1.3 on 2025-05-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projects_project_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
