# Generated by Django 5.0.2 on 2024-12-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="service_icon",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="services",
            name="service_title",
            field=models.CharField(max_length=255),
        ),
    ]
