# Generated by Django 5.0.2 on 2024-12-20 11:37

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_services_service_icon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="service_des",
            field=tinymce.models.HTMLField(),
        ),
    ]
