# Generated by Django 5.0.2 on 2024-12-24 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_blogdetail_blog_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="blogDetail",
            new_name="blogs",
        ),
    ]
