# Generated by Django 5.0.2 on 2024-12-28 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0005_blogs_blog_overview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogs",
            old_name="blog_date",
            new_name="blog_added_at",
        ),
    ]
