# Generated by Django 5.1.3 on 2025-05-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_rename_blog_date_blogs_blog_added_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogs',
            new_name='Blog',
        ),
    ]
