# Generated by Django 5.0.2 on 2024-12-27 07:32

import autoslug.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_title", models.CharField(max_length=255)),
                ("project_des", tinymce.models.HTMLField()),
                (
                    "project_slug",
                    autoslug.fields.AutoSlugField(
                        default=None,
                        editable=False,
                        null=True,
                        populate_from="project_title",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
