# Generated by Django 5.0.2 on 2024-12-28 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_projects_project_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="project_added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
