# Generated by Django 5.0.2 on 2024-12-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_projects_project_added_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="project_technology",
            field=models.CharField(max_length=255),
        ),
    ]
