# Generated by Django 5.0.2 on 2024-12-20 11:37

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="blogDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_title", models.CharField(max_length=255)),
                ("blog_des", tinymce.models.HTMLField()),
            ],
        ),
    ]
