# Generated by Django 5.0.2 on 2024-12-24 15:17

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0003_rename_blogdetail_blogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="blog_slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="blog_title",
                unique=True,
            ),
        ),
    ]
